// Code generated by MockGen. DO NOT EDIT.
// Source: workshop2/tokenizer (interfaces: Tokenizer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "workshop2/models"
	tokenizer "workshop2/tokenizer"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenizer is a mock of Tokenizer interface.
type MockTokenizer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenizerMockRecorder
}

// MockTokenizerMockRecorder is the mock recorder for MockTokenizer.
type MockTokenizerMockRecorder struct {
	mock *MockTokenizer
}

// NewMockTokenizer creates a new mock instance.
func NewMockTokenizer(ctrl *gomock.Controller) *MockTokenizer {
	mock := &MockTokenizer{ctrl: ctrl}
	mock.recorder = &MockTokenizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenizer) EXPECT() *MockTokenizerMockRecorder {
	return m.recorder
}

// ExtractClaims mocks base method.
func (m *MockTokenizer) ExtractClaims(arg0 string) (tokenizer.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractClaims", arg0)
	ret0, _ := ret[0].(tokenizer.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractClaims indicates an expected call of ExtractClaims.
func (mr *MockTokenizerMockRecorder) ExtractClaims(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractClaims", reflect.TypeOf((*MockTokenizer)(nil).ExtractClaims), arg0)
}

// Generate mocks base method.
func (m *MockTokenizer) Generate(arg0 tokenizer.Payload) (models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", arg0)
	ret0, _ := ret[0].(models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockTokenizerMockRecorder) Generate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockTokenizer)(nil).Generate), arg0)
}

// Verify mocks base method.
func (m *MockTokenizer) Verify(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenizerMockRecorder) Verify(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenizer)(nil).Verify), arg0)
}
