// Code generated by MockGen. DO NOT EDIT.
// Source: workshop2/services (interfaces: EventRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	models "workshop2/models"

	gomock "github.com/golang/mock/gomock"
)

// MockEventRepositoryInterface is a mock of EventRepositoryInterface interface.
type MockEventRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryInterfaceMockRecorder
}

// MockEventRepositoryInterfaceMockRecorder is the mock recorder for MockEventRepositoryInterface.
type MockEventRepositoryInterfaceMockRecorder struct {
	mock *MockEventRepositoryInterface
}

// NewMockEventRepositoryInterface creates a new mock instance.
func NewMockEventRepositoryInterface(ctrl *gomock.Controller) *MockEventRepositoryInterface {
	mock := &MockEventRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepositoryInterface) EXPECT() *MockEventRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventRepositoryInterface) Create(arg0 models.Event) (models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEventRepositoryInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepositoryInterface)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockEventRepositoryInterface) Delete(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventRepositoryInterfaceMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepositoryInterface)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockEventRepositoryInterface) Get(arg0 int) (models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEventRepositoryInterfaceMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEventRepositoryInterface)(nil).Get), arg0)
}

// GetAll mocks base method.
func (m *MockEventRepositoryInterface) GetAll() ([]models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEventRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEventRepositoryInterface)(nil).GetAll))
}

// Update mocks base method.
func (m *MockEventRepositoryInterface) Update(arg0 int, arg1 models.Event) (models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEventRepositoryInterfaceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventRepositoryInterface)(nil).Update), arg0, arg1)
}
